### ISSUE TITLE
GOES-16 Longitude 

### ISSUE THREAD

**Issue by mnichol3** [blaylockbk/pyBKB_v3#1] opened 2019-02-21 22:51 UTC
Hey Brian,

I'm writing code that deals with GOES-16 ABI & GLM imagery as well as aircraft observations as part of my senior research. I saw in your `mapping_GOES16_TrueColor.py` code, when getting GOES-16's Longitude of Projection Origin from the netCDF file, it will return `-75.0`. I originally got the same result in my own original code with the netCDFs I was processing.  However, GOES-16's longitude is -75.2. I found that this small difference in longitude resulted in a considerable amount of error when transforming the ABI coordinates to a Mercator projection and plotting aircraft-observed hurricane low pressure centers on top of the ABI images, more error than could have been attributed to just parallax. My advisor & I eventually figured out the problem and I hardcoded GOES-16's longitude at -75.2, which cleared things up. Just wanted to pass this along in-case you run into some discrepancies when working with GOES-16 imagery, especially on the mesoscale.

**Comment by blaylockbk** [comment] 2019-02-25 21:17
I haven't run into issues like this yet, but this is good to know. Thanks.

**Comment by blaylockbk** [comment] 2019-02-28 18:40
@mnichol3, I can confirmed the issue with the satellite longitude location. The left is GOES16 at -75.0 degrees, the right is GOES16 at -75.2 degrees. It is obvious that the drawn coastlines are wrong for the -75 degree location. The location metadata in the file is wrong! 
![image](https://user-images.githubusercontent.com/6249613/53589284-3a1c5780-3b4c-11e9-9981-12f11201c681.png)

This document shows that GOES-16 location is -75.2. (It looks like GOES-13 used to be at -75.0, which might be the source of the error). https://www.goes-r.gov/users/transitionToOperations16.html

The question is, how do we get the metadata fixed in the NetCDF files available on Amazon???
![image](https://user-images.githubusercontent.com/6249613/53589571-f2e29680-3b4c-11e9-8604-91394a465f7d.png)

**Comment by mnichol3** [comment] 2019-02-28 19:44
I downloaded another GOES-16 netCDF from NCDC to see if the longitude metadata error was unique to the Amazon files; the NCDC file had it too. 

![screenshot from 2019-02-28 14-33-35](https://user-images.githubusercontent.com/15006171/53593444-c6d40f00-3b66-11e9-9ca4-a7377e868646.png)

Not exactly sure how to go about addressing this issue, but I know some folks at NESDIS so I'll talk to them and see if they've heard anything about it!

**Comment by blaylockbk** [comment] 2019-02-28 19:47
That makes sense, since Amazon receives the files directly from them. 

I contacted the people I know, too. Maybe with several people hearing the issue it will be fixed soon.

I wonder if GOES-17 has a similar issue?

**Comment by blaylockbk** [comment] 2019-03-02 00:07
The answer I got from Tim Schmit (Twitter @GOESguy) is this:
> There are 2 longitudes, one is the location of the satellite, which is approximately 75.2W, the other, as you have noted above, that is the longitude of the remapped ABI data and that is in fact to 75.0W. Since you have remapped data, I think the 75.0W is the right value.

From that statement, I suspect the file's metadata should be trusted because the ABI data has been remapped to a common grid. However, that still doesn't explain why the coastlines I'm plotting appear misplaced. Perhaps there are issues when reprojection the image.

**Comment by mnichol3** [comment] 2019-03-07 18:54
I talked to Scott Rudlosky from NESDIS and he pretty much reiterated what Tim said, adding that Tim really knows his stuff. I agree that the metadata must be correct, but I'm still puzzled as to why the ABI imagery seems to contain more error than can be attributed to just parallax. I'll dig around and play around with reprojection functions some more and let you know if I come up with anything

**Comment by blaylockbk** [comment] 2019-05-15 17:59
It appears the issue depends on which map plotting tool you use. With Basemap, the coastlines are off, but with Cartopy, the coastlines are correct. 

With Cartopy:
![image](https://user-images.githubusercontent.com/6249613/57797851-9da83100-7708-11e9-8c7f-1c55275ace15.png) 

With Basemap:
![image](https://user-images.githubusercontent.com/6249613/57797965-d8aa6480-7708-11e9-96ef-6e2069ccfbfe.png)

**Closed as completed** 2019-08-08 16:32 UTC
